#!/bin/bash

ARG=$1

now_str () { date +%Y%m%d_%H%M%S; }
[[ -z "${ARG}" ]] && FILENAME="gen_$(now_str).ks"
[[ -z "${FILENAME}" ]] && FILENAME="${ARG}.ks"

(
echo -ne "#KSVER=RHEL7\n\n"
cat ks_gen_cfg
./ks_rootpw
./ks_sshpw

cat ks_install_src_el7

cat ks_part_vm

cat net_paoshift

cat ks_repo_epel

## add packages selections
echo '
###########################################################
%packages --ignoremissing --excludedocs
'
cat ks_pkg_generic_vm
echo '
%end
'
## create post section
echo '
###########################################################
%post --log=/root/ks.log
#!/bin/bash

'

cat ks_post_repo_elrepo
cat ks_post_pkg_elrepo

cat ks_post_repo_egicerts

cat ks_post_repo_umd
cat ks_post_pkg_umd_ui

cat ks_post_boot
cat ks_post_chrony
cat ks_post_dracut
cat ks_post_ssh
cat ks_post_update

echo '
echo "End of Kickstart"
%end

%addon com_redhat_kdump --disable
%end

'

) > ${FILENAME}

eval $(sed -n 's/#KSVER/KSVER/p' ${FILENAME})
[[ -n "${KSVER}" ]] && KSVALIDATEVER="-v ${KSVER}"

ksvalidator ${KSVALIDATEVER} ${FILENAME}

[[ "$(hostname -s)" != "monitor" ]] && scp ${FILENAME} monitor_root:/var/www/html/${FILENAME}

