#!/bin/sh

HOST_SHORT=$(/usr/bin/hostname -s)

# get interface of dhclient; the assuption is that dhclient serve only 1 interface
DH_INT=$(pgrep -a dhclient | awk '{print $NF}')

# assuption is that only one ip is set up on dhclient interface
IP_INT_LIST=$(/usr/sbin/ip -4 -o addr show dev ${DH_INT}| /usr/bin/grep -oP '(?<=inet\s)\d+(\.\d+){3}') ##'

# we want only private addresses (we expect that the public ones are registered in dns)
IP_INT_PRIV=$(grep -P '/(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)/' <<< "${IP_INT_LIST}") ##'

# IF there are multiple dhcp private ips on the interface lets select one
IP_PRIV=$(head -n1 <<<"${IP_INT_PRIV}")

/usr/bin/curl -fslk --header "Forwarded: ${IP_PRIV}" https://sev.spacescience.ro/dnsmasq/reg.php?${HOST_SHORT}

