#!/bin/sh
HOST_SHORT=$(/bin/hostname -s)

# get interface of dhclient; the assuption is that dhclient serve only 1 interface
DHCP_INT=$(ps --no-headers -o pid,args= $(pgrep dhclient) | awk '{print $NF}' | sort )

index="0"
for ETH in ${DHCP_INT} ; do
    # assuption is that only one ip is set up on dhclient interface
    IP_INT_LIST=$(/sbin/ip -4 -o addr show dev ${ETH}| /bin/grep -oP '(?<=inet\s)\d+(\.\d+){3}') #'

    # we want only private addresses (we expect that the public ones are registered in dns)
    IP_INT_PRIV=$(/bin/grep -P '/(^127\.)|(^192\.168\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)/' <<< "${IP_INT_LIST}") #'

    # IF there are multiple dhcp private ips on the interface lets select one
    IP_PRIV=$(/usr/bin/head -n1 <<< "${IP_INT_PRIV}")

    if [[ "${index}" -eq "0" ]]; then
        DNS_NAME="${HOST_SHORT}"
    else
        DNS_NAME="${HOST_SHORT}_${ETH}"
    fi

    /usr/bin/curl -fslk --header "Forwarded: ${IP_PRIV}" https://sev.spacescience.ro/dnsmasq/reg.php?${DNS_NAME}
    ((index++))
done

