#!/bin/bash

##ls -l /lib/modules/*/kernel/block/

sched=${1:-"mq-deadline"}

is_available=$(grep ${sched} /sys/block/sda/queue/scheduler)

if [[ -z "${is_available}" ]]; then
    modprobe ${sched}
    mod_name=$(modinfo ${sched} | awk -F":[[:space:]]*" '/^name/ {print $2}')

    is_present=$(lsmod | grep ${mod_name})
    [[ -z "${is_present}" ]] && { echo "scheduler module could not be loaded"; exit 1; }
fi

cpupower frequency-set -g performance  >/dev/null

for blk in /sys/block/s* ; do
    dev=$(basename ${blk})
    echo ${sched} > ${blk}/queue/scheduler
    echo 2048 > ${blk}/queue/nr_requests
    echo 4096 > ${blk}/queue/read_ahead_kb
    echo 512 >  ${blk}/queue/max_sectors_kb
done

