#!/bin/bash

enable_if_present () {
local eth tunable is_present
eth=${1}
tunable=${2}
is_present=$(ethtool -k ${eth} | grep ${tunable} | grep -v fixed)
[[ -n "${is_present}" ]] && ethtool -K ${eth} ${tunable} on
}

eth_list=$(find /sys/class/net -type l -not -lname '*virtual*' -printf '%f\n' | sort)

for eth in ${eth_list}; do

  # enable pausing of frames
  ethtool -A ${eth} autoneg on rx on tx on

  # enable adaptive coalescing
  #ethtool -C ${eth} adaptive-rx on adaptive-tx on

  ## settng of maximum ring size
  ETH_MAX_RING=$(ethtool -g ${eth} | grep -A 4 Pre-set | tail -n +2 | sed 's/:/=/;s/ /_/; s/\t//g;s/ //g')
  eval "${ETH_MAX_RING}"
  echo -n "Setting Ring parameters.."
  ethtool -G ${eth} rx "${RX}" tx "${TX}"
  echo " done!"
  #########

  ## settng of maximum number of channels
#  ETH_MAX_CHANNELS=$(ethtool -l ${eth} | grep -A 4 Pre-set | tail -n +2 | sed 's/:/=/;s/ /_/; s/\t//g;s/ //g')
#  eval "${ETH_MAX_CHANNELS}"
#  echo -n "Setting Channels parameters.."
#  ethtool -L ${eth} combined "${Combined}"
#  echo " done!"
  #########

  for i in rx-all rx tx sg rxhash; do ethtool -K ${eth} ${i} on; done

  # DEBATABLE
  #for i in tso ufo gso gro; do ethtool -K ${eth} ${i} on; done

  is_lro_present=$(ethtool -k ${eth} | grep large-receive-offload | grep -v fixed)
  [[ -n "${is_lro_present}" ]] && ethtool -K ${eth} lro on

  # DEBATABLE
  # ethtool -K ${eth} tx-nocache-copy

#  is_txchk_ipv4_present=$(ethtool -k ${eth} | grep tx-checksum-ipv4 | grep -v fixed)
#  [[ -n "${is_txchk_ipv4_present}" ]] && ethtool -K ${eth} tx-checksum-ipv4 on

#  is_txchk_ipv6_present=$(ethtool -k ${eth} | grep tx-checksum-ipv6 | grep -v fixed)
#  [[ -n "${is_txchk_ipv6_present}" ]] && ethtool -K ${eth} tx-checksum-ipv6 on

done

