#!/bin/bash

## for all storages ; mount point of storages is /storage*
for dev_storage in `df | grep storage | awk '{ print $1 }'`
do
  blockdev --setra 16384 $dev_storage

  dev=`echo $dev_storage | awk -F"/" '{print $3}' | cut -c -3`

  # set noop scheduler for raid storage
  echo noop > /sys/block/$dev/queue/scheduler

  # io requests queue
  echo 4096 > /sys/block/$dev/queue/nr_requests

done




