#!/bin/bash

DEV=$1
IP_MASK=$2
GW=$3
DNS=$4

nmcli con mod ${DEV} ipv4.method manual ipv4.addresses ${IP_MASK} ipv4.gateway ${GW} ipv4.dns ${DNS}
nmcli con mod ${DEV} connection.autoconnect yes
nmcli con reload
nmcli con show ${DEV} | grep ^ipv

echo -e "\nNow run :\nnmcli con up ${DEV}"

