#!/usr/bin/env bash

for int in $(nmcli -t con show --active | awk -F: '!/loop/{print $2}'); do
  nmcli connection modify ${int} 802-3-ethernet.mtu 9000
  nmcli connection modify ${int} ipv6.mtu 9000

  if [[ -d /etc/NetworkManager/dispatcher.d ]]; then
cat << "EOF" > /etc/NetworkManager/dispatcher.d/90-qlen
#!/usr/bin/env bash
export LC_ALL=C
[[ "${2}" == "up" ]] && /usr/sbin/ip link set "${1}" txqueuelen 20000
EOF
  fi
done
echo -e "Now run:\nnmcli con reload"
