#!/usr/bin/bash

set_repolink () {
local REPO="${1}"
local URL="${2}"
yum-config-manager --save --setopt=${REPO}.baseurl=${URL} &>/dev/null
yum-config-manager --save --setopt=${REPO}.mirrorlist="" &>/dev/null
yum-config-manager --save --setopt=${REPO}.keepcache=False &>/dev/null
}

set_repolink base           http://monitor.spacescience.ro/mirrors/centos/7/os/x86_64/
set_repolink updates        http://monitor.spacescience.ro/mirrors/centos/7/updates/x86_64/
set_repolink extras         http://monitor.spacescience.ro/mirrors/centos/7/extras/x86_64/
set_repolink centosplus     http://monitor.spacescience.ro/mirrors/centos/7/centosplus/x86_64/
set_repolink epel           http://monitor.spacescience.ro/mirrors/epel/7/x86_64/
set_repolink epel-debuginfo http://monitor.spacescience.ro/mirrors/epel/7/x86_64/debug/
set_repolink epel-source    http://monitor.spacescience.ro/mirrors/epel/7/SRPMS/

