#!/bin/bash

mkdir -p /root/bin
curl -fsSLk --create-dirs https://raw.githubusercontent.com/adriansev/ks_iss_repo/master/confs/rc.local/tweak_blockdev -o /root/bin/tweak_blockdev
chmod +x /root/bin/tweak_blockdev

cat > /etc/cron.d/tweak_io <<EOF
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
@reboot         /root/bin/tweak_blockdev &> /dev/null
0 */6 * * *     /root/bin/tweak_blockdev &> /dev/null

EOF

