#!/bin/bash

CURL="/usr/bin/curl -sfSLk"

VER=$(${CURL} http://download.virtualbox.org/virtualbox/LATEST.TXT)
DIR="http://download.virtualbox.org/virtualbox/${VER}/"

EXTPACK="Oracle_VM_VirtualBox_Extension_Pack-${VER}.vbox-extpack"

SUMS="SHA256SUMS"

${CURL} -O ${DIR}/${SUMS} -O ${DIR}/${EXTPACK}
REZ=$?
[[ ${REZ} != "0" ]] && { echo "DOWNLOAD FAILED!!!" && exit 1; }

grep "${EXTPACK}" ${SUMS} > MYSHA256SUMS_EXTPACK && rm -rf ${SUMS}

sha256sum -c MYSHA256SUMS_EXTPACK
REZ=$?
[[ ${REZ} != "0" ]] && { echo "SHA256 CHECKSUM FAILED!!!" && exit 1; }

vbox_installed=$(which VBoxManage 2>/dev/null)

if [[ -z "${vbox_installed}" ]]; then
  is_dnf=$(which dnf 2>/dev/null)
  INSTALL="yum"
  [[ -n "${is_dnf}" ]] && INSTALL="dnf"
  ${INSTALL} -y install elfutils-libelf-devel gcc make perl kernel-headers kernel-devel VirtualBox-5.2
fi

systemctl enable --now vboxdrv.service vboxautostart-service.service vboxballoonctrl-service.service vboxweb-service.service
systemctl restart systemd-modules-load.service

VBoxManage extpack install ${EXTPACK}

